name: Publish Release

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      - .github/workflows/*

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: get version
        id: version
        run: |
          echo "prop=$(jq -r '.version' version.json)" >> "$GITHUB_OUTPUT"
      - run: echo ${{ steps.version.outputs.prop }}
      - name: Create source archive
        run: |
          git archive --format=zip --output=voxkey.zip HEAD
      - name: Publish
        if: success()
        uses: softprops/action-gh-release@v2
        with:
          files: "voxkey.zip"
          tag_name: "v${{ steps.version.outputs.prop }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
